### ISSUE TITLE
Use my.cnf

### ISSUE THREAD

**Issue by santec** [martinarrieta/go-dump#10]
It would be useful if go-dump could read my.cnf in the same way mysqldump does.

**Comment by martinarrieta** [comment]
Agree, also I'm adding the option to add a new section `[go-dump]` to that file in order to overwrite the default parameters of the tool.

Thanks!

Martin.

**Comment by santec** [comment]
Very useful. If some options names are shared with `mysqldump` (and the semantics are the same), it could be useful to read `[mysqldump]` first, then `[go-dump]` (which overrides mysqldump settings).

**Comment by martinarrieta** [comment]
https://github.com/martinarrieta/go-dump/tree/ini-support 

Still need to make the tests and the documentation.. 😄

**Comment by martinarrieta** [comment]
This option is already working in the last release 0.0.7.

Regards, 

Martin.
