### ISSUE TITLE
Add instructions to compile this.

### ISSUE THREAD

**Issue by matteraf** [martinarrieta/go-dump#11]
Hi, please, add instructions to compile this.
Thanks.

**Comment by martinarrieta** [comment]
There is a release for each tag, those are builds that are ready to use and you don't need to compile anything. Please check [this link](https://github.com/martinarrieta/go-dump/releases)

The problem with go is that you need to setup your environment and if you are not a go-developer that can be a bit complex. 

That been said. 

As soon as you have go running (https://github.com/golang/go/wiki#working-with-go) , you can do:

```
git clone git@github.com:martinarrieta/go-dump.git 
cd go-dump
go get -t -v ./...
go run go/cmd/go-dump/main.go [parameters]
```

Regards, 

Martin.
