### ISSUE TITLE
Add a flag to choose isolation level

### ISSUE THREAD

**Issue by matteraf** [martinarrieta/go-dump#7]
Hi, please add a flag to choose isolation level.
I like to use READ COMMITTED, no matter consistency.

**Comment by martinarrieta** [comment]
Isolation level is requred for consistent backup, but I'm agree that it should be a user option.

**Comment by martinarrieta** [comment]
Work in progress here: https://github.com/martinarrieta/go-dump/tree/issolation-level

**Comment by martinarrieta** [comment]
The option was added. 

Closing issue.

**Comment by matteraf** [comment]
OK, and which is the flag and options to choose isolation level?
Version 0.5 adds this option?
